export { default as svChat } from './advanced-chat.webp';
export { default as astro } from './astro-spotify.webp';
export { default as calculator } from './calculator.webp';
export { default as chat } from './chat.webp';
export { default as images } from './images.png';
export { default as imgShare } from './imgshare.webp';
export { default as links } from './links.png';
export { default as shortener } from './shortener.png';
export { default as task } from './task.webp';
